'use client';

import { useEffect, useRef, useState } from 'react';
import { Button, Input, Space, Typography, Alert, App, Divider, Tooltip, Switch } from 'antd';
import {
  CopyOutlined,
  ExportOutlined,
  ReloadOutlined,
  MailOutlined,
  KeyOutlined,
} from '@ant-design/icons';
import { formatDateTime } from '@/lib/format';
import { ApiError, deleteJson, getJson, postJson } from '@/lib/api-fetch';

const { Text } = Typography;

export interface GarmentCompletenessSummary {
  total: number;
  /** Names of garments with no sizing/roster rows entered. */
  missingSizing: string[];
  /** Names of garments with no mock-up images uploaded. */
  missingImages: string[];
}

interface Props {
  orderId: string;
  customerEmail: string;
  hasActiveToken: boolean;
  tokenCreatedAt?: string | null;
  /**
   * The active link's URL, readable at rest (David, 2026-08-04) — null only
   * for links minted before the readable token column.
   */
  initialUrl?: string | null;
  /** Suppresses auto-generation and the action buttons — a cancelled order mints no links. */
  orderCancelled?: boolean;
  hasAccessCode?: boolean;
  /** Defaults to "complete" so callers/tests that don't care about this can omit it. */
  garmentSummary?: GarmentCompletenessSummary;
}

const DEFAULT_GARMENT_SUMMARY: GarmentCompletenessSummary = {
  total: 1,
  missingSizing: [],
  missingImages: [],
};

export function ShareLinkPanel({
  orderId,
  customerEmail,
  hasActiveToken,
  tokenCreatedAt,
  initialUrl = null,
  orderCancelled = false,
  hasAccessCode = false,
  garmentSummary = DEFAULT_GARMENT_SUMMARY,
}: Props) {
  const { message } = App.useApp();
  const [activeUrl, setActiveUrl] = useState<string | null>(initialUrl);
  const [hasToken, setHasToken] = useState(hasActiveToken);
  const [tokenDate, setTokenDate] = useState(tokenCreatedAt ?? null);
  const [codeEnabled, setCodeEnabled] = useState(hasAccessCode);
  const [activeCode, setActiveCode] = useState<string | null>(null);
  const [customCodeDraft, setCustomCodeDraft] = useState('');
  /** An active code from before the readable column — rotate to surface it. */
  const [legacyCode, setLegacyCode] = useState(false);
  const [loading, setLoading] = useState<'generate' | 'email' | 'code' | null>(null);

  // The stored code is staff-readable on demand — load it whenever a code is
  // enabled so it displays without a regenerate dance.
  useEffect(() => {
    if (!codeEnabled || activeCode) return;
    getJson<{ code: string | null; enabled: boolean; legacy: boolean }>(
      `/api/admin/orders/${orderId}/access-code`,
      'Failed to load the access code',
    )
      .then((res) => {
        if (res.code) setActiveCode(res.code);
        setLegacyCode(res.legacy);
      })
      .catch(() => {});
    // eslint-disable-next-line react-hooks/exhaustive-deps -- load once per enable
  }, [codeEnabled]);

  const noGarments = garmentSummary.total === 0;
  const incompleteGarments = [...new Set([...garmentSummary.missingSizing, ...garmentSummary.missingImages])];

  // The confirmation link IS this app's purpose — generate it on first view
  // instead of asking for a click (David, 2026-08-04). Whenever no URL is
  // visible, even if an old (pre-readable-column) link is technically active:
  // still in active dev, replacing it is fine (David, 2026-08-04).
  const autoGenerated = useRef(false);
  useEffect(() => {
    if (autoGenerated.current || activeUrl || noGarments || orderCancelled) return;
    autoGenerated.current = true;
    void generate();
    // eslint-disable-next-line react-hooks/exhaustive-deps -- once, on mount
  }, []);

  async function generate() {
    setLoading('generate');
    try {
      const data = await postJson<{ url: string }>(
        `/api/admin/orders/${orderId}/token`,
        undefined,
        'Failed to generate link',
      );
      setActiveUrl(data.url);
      setHasToken(true);
      setTokenDate(new Date().toISOString());
      message.success('Customer link generated');
      // Access codes default ON (David, 2026-08-04): a fresh link without a
      // code yet gets one automatically. Regenerated links keep their code.
      if (!codeEnabled) {
        try {
          const code = await postJson<{ code: string }>(
            `/api/admin/orders/${orderId}/access-code`,
            {},
            'Failed to set access code',
          );
          setActiveCode(code.code);
          setCodeEnabled(true);
        } catch {
          // Non-fatal: the link works; the staff can enable the code manually.
        }
      }
    } catch (err) {
      message.error(err instanceof Error ? err.message : 'Failed to generate link');
    } finally {
      setLoading(null);
    }
  }

  /** The link + code together, email-ready (David, 2026-08-04). */
  function emailSnippet(): string {
    return [
      'Please review and confirm your order here:',
      activeUrl ?? '',
      '',
      `Access code: ${activeCode ?? ''}`,
    ].join('\n');
  }

  async function copyEmailSnippet() {
    try {
      await navigator.clipboard.writeText(emailSnippet());
      message.success('Link and code copied — paste into your email');
    } catch {
      message.error('Copy failed — please copy manually');
    }
  }

  async function emailLink() {
    setLoading('email');
    try {
      const data = await postJson<{ url: string }>(
        `/api/admin/orders/${orderId}/send-link`,
        undefined,
        'Failed to send email',
      );
      // A new token was generated; update the displayed URL
      setActiveUrl(data.url);
      setHasToken(true);
      setTokenDate(new Date().toISOString());
      message.success(`Link emailed to ${customerEmail}`);
    } catch (err) {
      if (err instanceof ApiError && err.status === 503) {
        message.error('Email delivery is not configured on this server.');
        return;
      }
      message.error(err instanceof Error ? err.message : 'Failed to send email');
    } finally {
      setLoading(null);
    }
  }

  /**
   * Enable/rotate (no argument) or set a staff-chosen code. The stored code is
   * staff-readable afterwards (David, 2026-08-03) — no relay-it-now urgency.
   */
  async function setCode(customCode?: string) {
    setLoading('code');
    try {
      const data = await postJson<{ code: string }>(
        `/api/admin/orders/${orderId}/access-code`,
        customCode ? { code: customCode } : {},
        'Failed to set access code',
      );
      setActiveCode(data.code);
      setCodeEnabled(true);
      setCustomCodeDraft('');
      setLegacyCode(false);
      message.success('Access code set');
    } catch (err) {
      message.error(err instanceof Error ? err.message : 'Failed to set access code');
    } finally {
      setLoading(null);
    }
  }

  async function disableCode() {
    setLoading('code');
    try {
      await deleteJson(`/api/admin/orders/${orderId}/access-code`, undefined, 'Failed to remove access code');
      setActiveCode(null);
      setCodeEnabled(false);
      message.success('Access code removed — the link alone opens the order');
    } catch {
      // Match the pre-helper behavior: always the generic message.
      message.error('Failed to remove access code');
    } finally {
      setLoading(null);
    }
  }

  async function copyCode() {
    if (!activeCode) return;
    try {
      await navigator.clipboard.writeText(activeCode);
      message.success('Code copied to clipboard');
    } catch {
      message.error('Copy failed — please copy manually');
    }
  }

  return (
    <Space direction="vertical" style={{ width: '100%' }} size={16}>
      {noGarments && (
        <Alert
          type="error"
          showIcon
          message="This order has no garments"
          description="Add at least one garment before generating or sending a customer link."
        />
      )}

      {!noGarments && incompleteGarments.length > 0 && (
        <Alert
          type="warning"
          showIcon
          message="This order looks incomplete"
          description={
            <ul style={{ margin: '4px 0 0', paddingLeft: 20 }}>
              {garmentSummary.missingSizing.length > 0 && (
                <li>No sizing/roster entered: {garmentSummary.missingSizing.join(', ')}</li>
              )}
              {garmentSummary.missingImages.length > 0 && (
                <li>No mock-up image uploaded: {garmentSummary.missingImages.join(', ')}</li>
              )}
            </ul>
          }
        />
      )}

      {!activeUrl && !orderCancelled && (
        <Alert
          type="info"
          showIcon
          message="No customer link generated yet"
          description="Generate a link below to share with the customer, or use 'Email to customer' to generate and send it in one step."
        />
      )}

      {/* Same compact treatment as the roster page URL (David, 2026-08-04). */}
      {activeUrl && (
        <div>
          <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 8 }}>
            <Text strong>Customer link</Text>
            {tokenDate && (
              <Text type="secondary" style={{ fontSize: 12 }}>
                generated {formatDateTime(tokenDate)}
              </Text>
            )}
          </div>
          <Space wrap size={8}>
            <Text code copyable={{ text: activeUrl }} style={{ wordBreak: 'break-all' }}>
              {activeUrl}
            </Text>
            <Tooltip title="Opens the customer's page — note the order may show as 'viewed' once opened">
              <Button
                size="small"
                icon={<ExportOutlined />}
                href={activeUrl}
                target="_blank"
                rel="noopener noreferrer"
              >
                Open
              </Button>
            </Tooltip>
          </Space>
        </div>
      )}

      {/* Link + code together, ready to paste into an email (David, 2026-08-04). */}
      {activeUrl && activeCode && (
        <div
          style={{
            padding: '10px 14px',
            background: 'var(--ant-color-fill-tertiary)',
            border: '1px solid var(--ant-color-border)',
            borderRadius: 6,
          }}
        >
          <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 6 }}>
            <Text strong>For your email</Text>
            <Button type="primary" size="small" icon={<CopyOutlined />} onClick={copyEmailSnippet}>
              Copy link + code
            </Button>
          </div>
          <Text
            type="secondary"
            style={{ fontSize: 12, whiteSpace: 'pre-wrap', display: 'block', wordBreak: 'break-all' }}
          >
            {emailSnippet()}
          </Text>
        </div>
      )}

      <Divider style={{ margin: '4px 0' }} />

      {/* Regenerate/Revoke are gone (David, 2026-08-04): with the URL always
          visible there is nothing to re-surface, and killing a live link is a
          cancel-the-order concern, not a panel button. Generate remains only
          as the retry path when auto-generation could not run. */}
      {orderCancelled && (
        <Alert type="info" showIcon message="This order is cancelled — its customer link is revoked and no new one can be generated." />
      )}

      <Space wrap>
        {!activeUrl && !orderCancelled && (
          <Tooltip title={noGarments ? 'Add at least one garment first' : undefined}>
            <Button
              icon={<ReloadOutlined />}
              loading={loading === 'generate'}
              disabled={noGarments || (loading !== null && loading !== 'generate')}
              onClick={generate}
            >
              Generate link
            </Button>
          </Tooltip>
        )}

        <Tooltip
          title={
            noGarments ? 'Add at least one garment first' : `Generates a fresh link and emails it to ${customerEmail}`
          }
        >
          <Button
            icon={<MailOutlined />}
            loading={loading === 'email'}
            disabled={noGarments || orderCancelled || (loading !== null && loading !== 'email')}
            onClick={emailLink}
          >
            Email to customer
          </Button>
        </Tooltip>
      </Space>

      <Divider style={{ margin: '4px 0' }} />

      {/* ── Optional per-order access code ── */}
      <div>
        <div style={{ display: 'flex', alignItems: 'flex-start', gap: 12 }}>
          <Tooltip title={!hasToken ? 'Generate a customer link first' : undefined}>
            <Switch
              checked={codeEnabled}
              loading={loading === 'code'}
              disabled={!hasToken || (loading !== null && loading !== 'code')}
              onChange={(checked) => (checked ? setCode() : disableCode())}
            />
          </Tooltip>
          <div>
            <Text strong>
              <KeyOutlined style={{ marginRight: 6 }} />
              Require access code
            </Text>
            <Text type="secondary" style={{ fontSize: 12, display: 'block', marginTop: 2 }}>
              The customer must also enter a code to open the order. Relay it by phone or text —
              it is never emailed with the link, and it stays the same if a fresh link is emailed.
            </Text>
          </div>
        </div>

        {activeCode && (
          <div style={{ marginTop: 12 }}>
            <div
              style={{
                display: 'flex',
                alignItems: 'center',
                gap: 8,
                padding: '8px 12px',
                background: 'var(--ant-color-fill-tertiary)',
                borderRadius: 6,
                border: '1px solid var(--ant-color-border)',
              }}
            >
              <KeyOutlined style={{ color: 'var(--ant-color-primary)', flexShrink: 0 }} />
              <Text strong style={{ flex: 1, fontSize: 18, letterSpacing: 2 }}>
                {activeCode}
              </Text>
              <Button type="primary" size="small" icon={<CopyOutlined />} onClick={copyCode}>
                Copy
              </Button>
            </div>
          </div>
        )}

        {legacyCode && !activeCode && (
          <Alert
            style={{ marginTop: 12 }}
            type="warning"
            showIcon
            icon={<KeyOutlined />}
            message="A code is active but was set before codes became viewable"
            description="Set a new one below to see it here (the old code stops working)."
          />
        )}

        {codeEnabled && (
          <Space style={{ marginTop: 12 }} wrap>
            <Input
              size="small"
              placeholder="Custom code (4+ characters)"
              value={customCodeDraft}
              onChange={(e) => setCustomCodeDraft(e.target.value)}
              onPressEnter={() => customCodeDraft.trim().length >= 4 && void setCode(customCodeDraft)}
              style={{ width: 220 }}
              maxLength={64}
            />
            <Button
              size="small"
              loading={loading === 'code'}
              disabled={customCodeDraft.trim().length < 4 || (loading !== null && loading !== 'code')}
              onClick={() => void setCode(customCodeDraft)}
            >
              Set custom code
            </Button>
            <Button
              size="small"
              loading={loading === 'code'}
              disabled={loading !== null && loading !== 'code'}
              onClick={() => void setCode()}
            >
              Generate random
            </Button>
          </Space>
        )}
      </div>
    </Space>
  );
}
